title: Software Development Blog
author: Andreas Valsamis
email: andvalsamis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
A blog about Web development.

# social links
twitter_username: your-twitter-void
github_username:  AndValsamis

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
