title: Your awesome title
author: Andreas Valsamis
email: AndValsamis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a personal blog about software development.

# social links
twitter_username: twitter-handle-void
github_username:  AndValsamis

show_excerpts: true # set to false to remove excerpts on the homepage

theme:minima 
